tienda/productos/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from .views import (
    ProductoList,
    # ProductoDetail,
    ProductoCreation,
    ProductoUpdate,
    ProductoDelete
)
urlpatterns = [
    url(r'^$',views.principal, name='principal'),
    url(r'^inicio/',views.inicio, name='inicio'),
    url(r'^Lista/Productos/',views.ProductoList, name='producto_list'),
    # url(r'^Lista/Productos/', login_required(ProductoList.as_view()), name='list'),
    # url(r'^(?P<pk>\d+)', views.ProductoDetail, name='detail'),
    url(r'^Producto/(?P<pk>[0-9]+)/$',views.ProductoDetail,name='producto_detail'),
    url(r'^Producto/Nuevo',views.producto,name="producto"),
    url(r'^Categoria/Nueva',views.categoria,name="categoria"),
    url(r'^Venta/Nueva',views.venta,name="venta"),
    url(r'^Lista/Ventas/',views.listaventas,name="listaventas"),
    # url(r'^Pdf',views.pdf,name="pdf"),
    # url(r'^Grafica',views.grafica,name="grafica"),
    url(r'^Editar/(?P<pk>\d+)', login_required(ProductoUpdate.as_view()), name='edit'),
    url(r'^Borrar/(?P<pk>\d+)', login_required(ProductoDelete.as_view()), name='delete'),
    url(r'^Pdf/Dia',views.pdfdia,name="pdfdia"),
    url(r'^Pdf/General',views.pdfgen,name="pdfgen"),
    url(r'^Pdf/Grafica',views.grafica_pastel,name="pastel"),
    # url(r'^Venta/',views.venta,name="venta"),
    # url(r'^seller/$', views.seller_list, name='seller_list'),
    # url(r'^seller/(?P<id>[0-9]+)/$', views.seller_detail, name='seller_detail'),
]

tienda/tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('productos.urls', namespace='home')),
    url(r'^accounts/', include('registration.backends.default.urls')),
 # 	url(r'^clientes/', include('clientes.urls', namespace='clientes')),
    # url(r'^proveedores/', include('proveedores.urls', namespace='proveedores')),
 	url(r'^productos/', include('productos.urls', namespace='productos')),
    # url(r'^productos/', include('productos.urls', namespace='producto')),
]

tienda/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>{% block head_title %}Jimmy's Store {% endblock %}</title>
    <style>
    {% block style %}{% endblock %}
    </style>
    {% include "head_css.html" %}
  </head>
  <body>
    {% include "navbar.html" %}
{% block jumbotron %}
{% endblock %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div> <!-- /container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

tienda/templates/head_css.html
{% load static %}
<!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://use.fontawesome.com/813af290c9.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script> -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

tienda/templates/home.html
{% extends 'base.html' %}
  <meta charset="UTF-8">
  {% block title %}Inicio{% endblock %}
  {% block content %}
  {% load bootstrap3 %}
  {% load i18n %}
  {% if request.user.is_authenticated %}
                <h1 align="center">Bienvenido {% firstof request.user.get_short_name request.user.get_username %}</h1>
                <br>
                <h4 align="center">
                  Nos encontramos en Colonia Centro C.P:16000 Calle Republica del Salvador CDMX
                </h4>
                <br>
                <h4 align="center">
                  Tu mejor opción en esta epoca donde la tecnología y pensando en un futuro chido!
                </h4>
                <br>
                <br>
                <div class="col-sm-12" align="center">
                  <p class="lead text-align-center">Jimmy's Store<br><br><span class="fa-stack fa-5x">
                    <i class="fa fa-circle-o-notch fa-stack-2x" style="color:yellow;"></i>
                    <i class="fa fa-code fa-stack-1x" style="color:darkblue;"></i></span>
                  </p>
                </div>
                {% else %}
                <h1 align="center">Bienvenido de nuevo</h1>
                <h2 align="center">Jimmy's Store</h2>
                <div class="col-sm-12" align="center">
                  <p class="lead text-align-center"><br><br><span class="fa-stack fa-5x">
                    <i class="fa fa-circle-o-notch fa-stack-2x" style="color:yellow;"></i>
                    <i class="fa fa-code fa-stack-1x" style="color:darkblue;"></i></span>
                  </p>
                </div>
                {% endif %}
{% endblock %}

tienda/templates/inicio.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}Store{% endblock %}
{% block jumbotron %}
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1 style="color:white">Store</h1>
				<p style="color:white">Esta es la Tipica tienda que te vende lo que buscas a precios accesibles cerca de tu hogar</p>
					<a class="btn btn-lg btn-success" href="" role="button">Conócenos</a>
				</p>
			</div>

			<div class="col-sm-6"><iframe width="560" height="315" src="https://www.youtube.com/embed/SV7Hg23gF-s" frameborder="0" allowfullscreen></iframe></div>
		</div>
	</div>
</div>
      {% endblock %}
      <!-- <h1>Hello puto mundo</h1> -->
<hr/>
<br/>
{% block content %}
<div class="row">
	<div class="col-sm-3 col-xs-12 pull-right">
		<p class="lead text-align-center">
		<span class="fa-stack fa-lg">
			<i class="fa fa-spinner fa-spin fa-stack-2x"></i>
			<i class="fa fa-whatsapp fa-stack-1x"></i>
		</span></p>
		</br>
	</div>
	<div class="col-sm-3">
		<p class="lead text-align-center">Visión</br><i class="fa fa-code fa-3x" aria-hidden="true"></i></p>
	</div>
	<div class="col-sm-3">
	<p class="lead text-align-center">Misión</p>
	</div>
	<div class="col-sm-3">
	<p class="lead text-align-center">Valores</br><i class="fa fa-spinner fa-spin fa-3x fa-fw"></i></p>
	</div>
</div>
{% endblock %}

tienda/templates/navbar.html
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "productos:principal" %}">Jimmy's Store</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url "productos:principal" %}"><i class="fa fa-linux fa-lg" aria-hidden="true"></i>Inicio</a></li>
            {% if request.user.is_authenticated %}
            <li><a class="fa fa-list" href="{% url "productos:producto_list" %}"> Lista de Productos</a></li>
            {% if request.user.is_superuser %}
            <li><a class="fa fa-th-list" href="{% url "productos:listaventas" %}"> Lista de Ventas</a><li>
            <li><a class="fa fa-arrow-up" href="{% url "productos:producto" %}"> Productos</a>
            <li><a class="fa fa-upload" href="{% url "productos:categoria" %}"> Categoria</a></li>
            <!-- <li><a class="fa fa-file-pdf-o" href="{% url "productos:pdfdia" %}"> Ventas del Dia</a></li> -->
    			  <!-- <li><a class="fa fa-file-pdf-o" href="{% url "productos:pdfgen" %}"> Ventas en General</a></li> -->
            <li><a class="fa fa-pie-chart" href="{% url "productos:pastel" %}"> Grafica</a></li>

              {% else %}
              {% endif %}</li>
            {% else %}

            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'auth_logout' %}"><i class="fa fa-times-circle" aria-hidden="true"></i> Cerrar Sesión</a></li>
            {% else %}
            <li><a href="{% url 'registration_register' %}"><i class="fa fa-user-circle" aria-hidden="true"></i> Registrate</a></li>
           <!--  <li><a href="{% url 'auth_login' %}">Iniciar Sesión</a></li> -->
            {% endif %}
          </ul>
          {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
          <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}">
          {% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" name="username" placeholder="Usuario">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" name="password" placeholder="Contraseña">
            </div>
            <button type="submit" class="btn btn-success">Entrar</button>
          </form>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>