tienda/productos/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from .views import (
    ProductoList,
    # ProductoDetail,
    ProductoCreation,
    ProductoUpdate,
    ProductoDelete
)
urlpatterns = [
    url(r'^$',views.principal, name='principal'),
    url(r'^inicio/',views.inicio, name='inicio'),
    url(r'^Lista/Productos/',views.ProductoList, name='producto_list'),
    # url(r'^Lista/Productos/', login_required(ProductoList.as_view()), name='list'),
    # url(r'^(?P<pk>\d+)', views.ProductoDetail, name='detail'),
    url(r'^Producto/(?P<pk>[0-9]+)/$',views.ProductoDetail,name='producto_detail'),
    url(r'^Producto/Nuevo',views.producto,name="producto"),
    url(r'^Categoria/Nueva',views.categoria,name="categoria"),
    url(r'^Venta/Nueva',views.venta,name="venta"),
    url(r'^Lista/Ventas/',views.listaventas,name="listaventas"),
    # url(r'^Pdf',views.pdf,name="pdf"),
    # url(r'^Grafica',views.grafica,name="grafica"),
    url(r'^Editar/(?P<pk>\d+)', login_required(ProductoUpdate.as_view()), name='edit'),
    url(r'^Borrar/(?P<pk>\d+)', login_required(ProductoDelete.as_view()), name='delete'),
    url(r'^Pdf/Dia',views.pdfdia,name="pdfdia"),
    url(r'^Pdf/General',views.pdfgen,name="pdfgen"),
    url(r'^Pdf/Grafica',views.grafica_pastel,name="pastel"),
    # url(r'^Venta/',views.venta,name="venta"),
    # url(r'^seller/$', views.seller_list, name='seller_list'),
    # url(r'^seller/(?P<id>[0-9]+)/$', views.seller_detail, name='seller_detail'),
]

tienda/tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('productos.urls', namespace='home')),
    url(r'^accounts/', include('registration.backends.default.urls')),
 # 	url(r'^clientes/', include('clientes.urls', namespace='clientes')),
    # url(r'^proveedores/', include('proveedores.urls', namespace='proveedores')),
 	url(r'^productos/', include('productos.urls', namespace='productos')),
    # url(r'^productos/', include('productos.urls', namespace='producto')),
]

tienda/productos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Venta(models.Model):
	fecha = models.DateField(auto_now_add=True)
	producto = models.ForeignKey('Producto', null=True, blank=True, on_delete=models.CASCADE)
	cantidad_vendida = models.IntegerField()

	def __str__(self):
		return self.producto

class Categoria(models.Model):
	categoria = models.CharField(max_length=255)

	def __str__(self):
		return self.categoria


class Producto(models.Model):
	codigo_p = models.IntegerField(null=False, blank=False, unique=True)
	nombre = models.CharField(max_length=255, null=False, blank=False)
	descripcion = models.CharField(max_length=255)
	categoria = models.ForeignKey(Categoria, null=True, blank=True, on_delete=models.CASCADE)
	unidades = models.IntegerField(null=False, blank=False)
	precio = models.DecimalField(max_digits=9,decimal_places=2, null=False, blank=False)

	def __str__(self):
		return self.nombre

tienda/productos/forms.py
from django import forms
from .models import Producto, Categoria, Venta
from django.forms import ModelForm, Textarea, DateInput, NumberInput, SelectDateWidget

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        widgets = {
            'descripcion': Textarea(attrs={'cols': 40, 'rows': 15})
        }

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'

class VentaForm(ModelForm):
    class Meta:
        model = Venta
        fields = '__all__'
        widgets = {
        	'fecha': SelectDateWidget(),
            'cantidad_vendida': NumberInput(attrs={'value': 0})
        }

tienda/productos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Producto, Categoria, Venta
from .forms import ProductoForm, CategoriaForm, VentaForm

from django.db.models import Sum, Count
import pprint
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)
import os
from reportlab.pdfgen import canvas
from django.views.generic import ListView
from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Table
from io import BytesIO
from reportlab.lib.colors import PCMYKColor
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from django.db.models import Q
#pastel
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.legends import Legend
import time


def ProductoList(request):
    latest_alcohol_list = Producto.objects.order_by('id')[:9]
    context = {
        'latest_alcohol_list':latest_alcohol_list
    }
    print (latest_alcohol_list)
    return render(request, 'productos/producto_list.html', context)

def ProductoDetail(request,pk):
    producto = get_object_or_404(Producto, pk=pk)
    template = loader.get_template('productos/producto_detail.html')
    forma = VentaForm(request.POST, request.FILES)
    if forma.is_valid():
        cantidad_vendida = forma.cleaned_data['cantidad_vendida']
        venta = Venta()
        producto.unidades = producto.unidades - cantidad_vendida
        venta.producto = producto
        venta.cantidad_vendida = cantidad_vendida
        producto.save()
        venta.save()
    context = {
    'forma': forma,
    'producto': producto
    }
    if request.user.is_authenticated():
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponseRedirect(reverse('productos/producto_detail.html', args=(producto.id,)))

class ProductoCreation(CreateView):
    model = Producto
    success_url = reverse_lazy('productos:producto_list')
    fields = ['codigo_p', 'nombre', 'descripcion', 'categoria', 'unidades', 'precio']
class ProductoUpdate(UpdateView):
    model = Producto
    success_url = reverse_lazy('productos:producto_list')
    fields = ['codigo_p', 'nombre', 'descripcion', 'categoria', 'unidades', 'precio']
class ProductoDelete(DeleteView):
    model = Producto
    success_url = reverse_lazy('productos:producto_list')
    fields = ['codigo_p', 'nombre', 'descripcion', 'categoria', 'unidades', 'precio']

def principal(request):
    playera = Producto.objects.order_by('id')
    template = loader.get_template('home.html')
    context = {
        'playera': playera
    }
    return HttpResponse(template.render(context, request))

def inicio(request):
    playera = Producto.objects.order_by('id')
    template = loader.get_template('inicio.html')
    context = {
        'playera': playera
    }
    return HttpResponse(template.render(context, request))

def producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            playera = form.save()
            playera.save()
            return HttpResponseRedirect('/productos/Lista/Productos/')
    else:
        form = ProductoForm()
    template = loader.get_template('productos/new_producto.html')
    context = {
        'form': form
    }
    if request.user.is_authenticated():
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponseRedirect('productos:producto_list')

def categoria(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST, request.FILES)
        if form.is_valid():
            playera = form.save()
            playera.save()
            return HttpResponseRedirect('/productos/Lista/Productos/')
    else:
        form = CategoriaForm()
    template = loader.get_template('productos/new_categoria.html')
    context = {
        'form': form
    }
    if request.user.is_authenticated():
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponseRedirect('productos:productos_list')


def venta(request):
    if request.method == 'POST':
        form = VentaForm(request.POST, request.FILES)
        if form.is_valid():
            playera = form.save()
            playera.save()
            return HttpResponseRedirect('/productos/Lista/Productos/')
    else:
        form = VentaForm()
    template = loader.get_template('productos/new_venta.html')
    context = {
        'form': form
    }
    if request.user.is_authenticated():
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponseRedirect('producto:detail')

def listaventas(request):
    playera = Venta.objects.order_by('id')
    template = loader.get_template('productos/venta_list.html')
    context = {
        'playera': playera
    }
    return HttpResponse(template.render(context, request))

# def grafica(request):
#     print "Genero el PDF[grafica]"
#     response = HttpResponse(content_type='application/pdf')
#     pdf_name = "Grafica.pdf"  # llamado clientes
#     # la linea 26 es por si deseas descargar el pdf a tu computadora
#     response['Content-Disposition'] = 'attachment; filename=%s' % pdf_name
#     buff = BytesIO()
#     doc = SimpleDocTemplate(buff,
#                             pagesize=letter,
#                             rightMargin=40,
#                             leftMargin=40,
#                             topMargin=60,
#                             bottomMargin=18,
#                             )
#     courses = []
#     styles = getSampleStyleSheet()
#     header = Paragraph("Total de Cursos", styles['Heading2'])
#     courses.append(header)
#     styles = getSampleStyleSheet()
#     d = Drawing(600, 300)
#     conteo = Course.objects.count()
#     # for i in Course.objects.all():
#     # print conteo
#     data = [(conteo,)]
#     bc = VerticalBarChart()
#     bc.x = 50
#     bc.y = 50
#     bc.height = 200
#     bc.width = 300
#     bc.data = data
#     bc.strokeColor = colors.blue
#     bc.valueAxis.valueMin = 0
#     bc.valueAxis.valueMax = 10
#     bc.valueAxis.valueStep = 1  #paso de distancia entre punto y punto
#     bc.categoryAxis.labels.boxAnchor = 'ne'
#     bc.categoryAxis.labels.dx = 8
#     bc.categoryAxis.labels.dy = -2
#     bc.categoryAxis.labels.angle = 30
#     bc.categoryAxis.categoryNames = ['Cursos']
#     bc.groupSpacing = 10
#     bc.barSpacing = 2
#     d.add(bc)
#     pprint.pprint(bc.getProperties())
#     courses.append(d)
#     doc.build(courses)
#     response.write(buff.getvalue())
#     buff.close()
#     return response
#
# def pdf(request):
#     print "Genero el PDF"
#     response = HttpResponse(content_type='application/pdf')
#     pdf_name = "Lista de Cursos.pdf"  # llamado clientes
#     # la linea 26 es por si deseas descargar el pdf a tu computadora
#     response['Content-Disposition'] = 'attachment; filename=%s' % pdf_name
#     buff = BytesIO()
#     doc = SimpleDocTemplate(buff,
#                             pagesize=letter,
#                             rightMargin=40,
#                             leftMargin=40,
#                             topMargin=60,
#                             bottomMargin=18,
#                             )
#     courses = []
#     styles = getSampleStyleSheet()
#     header = Paragraph("Lista de Cursos", styles['Heading2'])
#     courses.append(header)
#     headings = ('Nombre', 'Fecha de Inicio', 'Fecha de fin', 'Imagen')
#     allcourses = [(p.Nombre, p.Fecha_inicio, p.Fecha_fin,  p.Imagen) for p in Course.objects.all()]
#     print allcourses
#     t = Table([headings] + allcourses)
#     t.setStyle(TableStyle(
#         [
#             ('GRID', (0, 0), (3, -1), 1, colors.dodgerblue),
#             ('LINEBELOW', (0, 0), (-1, 0), 2, colors.darkblue),
#             ('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue)
#         ]
#     ))
#
#     courses.append(t)
#     doc.build(courses)
#     response.write(buff.getvalue())
#     buff.close()
#     return response

def pdfgen(request):
    print "Genero el PDF Ventas en General"
    response = HttpResponse(content_type='application/pdf')
    pdf_name = "Reporte_de_Ventas_General.pdf"  # llamado clientes
    # la linea 26 es por si deseas descargar el pdf a tu computadora
    # response['Content-Disposition'] = 'attachment; filename=%s' % pdf_name
    buff = BytesIO()
    doc = SimpleDocTemplate(buff,
                            pagesize=letter,
                            rightMargin=40,
                            leftMargin=40,
                            topMargin=60,
                            bottomMargin=18,
                            )
    courses = []
    styles = getSampleStyleSheet()
    header = Paragraph("Reporte General de Ventas.", styles['Heading2'])
    courses.append(header)
    headings = ('Id', 'Producto', 'Cantidad Vendida', 'Fecha')
    allcourses = [(p.id, p.producto, p.cantidad_vendida, p.fecha) for p in Venta.objects.all()]
    # print allcourses
    t = Table([headings] + allcourses)
    t.setStyle(TableStyle(
        [
            ('GRID', (0, 0), (3, -1), 1, colors.green),
            ('LINEBELOW', (0, 0), (-1, 0), 2, colors.green),
            ('BACKGROUND', (0, 0), (-1, 0), colors.green)
        ]
    ))

    courses.append(t)
    doc.build(courses)
    response.write(buff.getvalue())
    buff.close()
    return response


def pdfdia(request):
    # print "Genero el PDF Ventas del Dia"

tienda/templates/productos/new_categoria.html
	{% extends 'base.html' %}
	<meta charset="UTF-8">
	{% block head_title %}Agregar Categoria{% endblock %}
	{% block content %}
	{% load bootstrap3 %}
	{% load crispy_forms_tags %}
	{% load i18n %}
	{{ form.media }}
	{% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1 align="center" style="color:white;">Agregar categoria</h1>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
				<button type="submit" class="btn btn-success" style="background-color: #338A11; border-color:#1bf10a;">Agregar</button>
				{% endbuttons %}
			</form>
		</div>
	</div>
{% endblock %}

tienda/templates/productos/new_producto.html
	{% extends 'base.html' %}
	<meta charset="UTF-8">
	{% block head_title %}Agregar Producto{% endblock %}
	{% block content %}
	{% load bootstrap3 %}
	{% load crispy_forms_tags %}
	{% load i18n %}
	{{ form.media }}
	{% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1 align="center" style="color:white;">Agregar Producto</h1>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
				<button type="submit" class="btn btn-success" style="background-color: #338A11; border-color:#1bf10a;">Agregar</button>
				{% endbuttons %}
			</form>
		</div>
	</div>
{% endblock %}

tienda/templates/productos/new_venta.html
	{% extends 'base.html' %}
	<meta charset="UTF-8">
	{% block head_title %}Vender{% endblock %}
	{% block content %}
	{% load bootstrap3 %}
	{% load crispy_forms_tags %}
	{% load i18n %}
	{{ form.media }}
	{% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1 align="center">Agregar Venta</h1>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
				<p><label for="number">Total: <input type="number" name="number" id="total1" value="0" readonly></label></p>
				<button type="submit" class="btn btn-success">{% bootstrap_icon "plus" %}Agregar</button>
				{% endbuttons %}
			</form>
		</div>
	</div>
	<script type="text/javascript">
	    $('#id_cantidad_vendida').bind('input', function() {
	        qty = $(this).val() // get the current value of the input field.
	        document.getElementById("total1").value = (1*qty);
	});
	</script>
{% endblock %}

tienda/templates/productos/producto_confirm_delete.html
{% extends 'base.html' %}
	{% block head_title %}Eliminar {{ producto.Medida_Diametro }}{% endblock %}
	{% block content %}
	{% load bootstrap3 %}
	{% load crispy_forms_tags %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<form method="post">{% csrf_token %}
				<h1>¿Estás seguro que deseas borrar el curso "{{ producto.nombre }} {{ producto.descripcion }}?"</h1>
				<br>
				<input type="submit" value="Borrar" class="btn btn-success" style="background-color: darkred; border-color: red;"/>
			</form>
		</div>
	</div>
	{% endblock %}

tienda/templates/productos/producto_detail.html
{% extends 'base.html' %}
	{% block head_title %}Detalle del Producto{% endblock %}
	<style>
	body{
		background-color: black!important;
		color: white!important;
	}
	</style>
	{% block content %}
	{% load bootstrap3 %}
	{% load staticfiles %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
			<h1 style="color:white;">Detalle</h1>
			<h1 style="color:white;">Vendedor {% firstof request.user.get_short_name request.user.get_username %}</h1>
			<h4 style="color:white;">Nombre: {{ producto.nombre }}</h1>
			<h4 style="color:white;">Descripción: {{ producto.descripcion }}</h1>
			<h4 style="color:white;">Categoria: {{ producto.categoria }}</h2>
			<p>
				Precio: ${{ producto.precio }}
			</p>
			<h4 style="color:white;">Comprar</h4>
			<form method="post" class="form" style="color:black;">
				{% csrf_token %}
				<p>{{ forma.fecha }}</p>
				<!-- <p>{{ forma.producto }}</p> -->
				<p>{{ forma.cantidad_vendida}}</p>
				<p><label for="number" style="color:white;">Total: <input style="color:black;" type="number" name="number" id="total1" value="0" readonly></label></p>
	    <td><a href="{% url "productos:producto_list" %}"><input style="background-color: #E69005; border-color: #f5a309;" type="submit" value="Comprar" class="btn btn-success"/></a></td>
	</form>
<div align="left">
		{% buttons %}

			{% if request.user.is_superuser %}
			<a href="{% url "productos:edit" producto.id %}"><button type="submit" class="btn btn-success" style="background-color: #338A11; border-color:#1bf10a;">Editar</button></a>
			<a href="{% url "productos:producto_list" %}"><button type="submit" class="btn btn-success" style="background-color: #338A11; border-color:#1bf10a;">Regresar</button></a>
			{% else %}
			<a href="{% url "productos:producto_list" %}">
				<button type="submit" class="btn btn-success">Regresar</button>
			</a>
			{% endif %}
        {% endbuttons %}
			</div>
		</div>
	</div>
	<script type="text/javascript">
	    $('#id_cantidad_vendid').bind('input', function() {
	        qty = $(this).val() // get the current value of the input field.
	        document.getElementById("total1").value = ({{producto.precio}}*qty);
	});
	</script>
{% endblock %}


2017-03-17 15:06

tienda/templates/productos/producto_form.html
{% extends 'base.html' %}
	{% block head_title %}Agregar y Editar{% endblock %}
	{% load bootstrap3 %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}

	{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
			<h1 style="color:white;">Agregar/Editar Producto</h1>
			<form method="post">
				{% csrf_token %}
				{% bootstrap_form form %}
				<input type="submit" value="Agregar/Editar" class="btn btn-success" style="background-color: #338A11; border-color:#1bf10a;"/>
			</form>
		</div>
	</div>
{% endblock %}

tienda/templates/productos/producto_list.html
{% extends 'base.html' %}
	{% block head_title %}Lista de Productos{% endblock %}
	{% block content %}
  {% load bootstrap3 %}
	<script type="text/javascript">
(function(document) {
  'use strict';

  var LightTableFilter = (function(Arr) {

    var _input;

    function _onInputEvent(e) {
      _input = e.target;
      var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
      Arr.forEach.call(tables, function(table) {
        Arr.forEach.call(table.tBodies, function(tbody) {
          Arr.forEach.call(tbody.rows, _filter);
        });
      });
    }

    function _filter(row) {
      var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
      row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
    }

    return {
      init: function() {
        var inputs = document.getElementsByClassName('light-table-filter');
        Arr.forEach.call(inputs, function(input) {
          input.oninput = _onInputEvent;
        });
      }
    };
  })(Array.prototype);

  document.addEventListener('readystatechange', function() {
    if (document.readyState === 'complete') {
      LightTableFilter.init();
    }
  });

})(document);
</script>
<style type="text/css">
#cuadro{
	width: 90%;
	background: #F8F8F8 ;
	padding: 25px;
	margin: 5px auto;
	border: 3px solid #D8D8D8;
}

#buscar{
	width: 300px;
	font-size: 22px;
	color: #fff;
	background: #383838 ;
	padding-left: 20px ;
	text-align: center;
	border-radius: 5px;
	padding: 10px;
	margin:10px;
}

	</style>

	<div class="row">
		<div align="center">
			<h1 style="color:white;">Lista de Productos</h1>
			{% load staticfiles %}
			<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
			<div class="derecha" id="buscar">Buscar <input style="color:black;" type="search" class="light-table-filter" data-table="order-table" placeholder="Buscar"></div>{% if request.user.is_superuser %}{% else %}{% endif %}</div>
			<table class="order-table table">
					<thead>

						<th align="center" style="vertical-align:middle"><h1 class="h4">Código</h1><th>
						<th align="center" style="vertical-align:middle"><h1 class="h4">Nombre</h1><th>
            <th align="center" style="vertical-align:middle"><h1 class="h4">Descripción</h1><th>
            <th align="center" style="vertical-align:middle"><h1 class="h4">Categoría</h1><th>
						<th align="center" style="vertical-align:middle"><h1 class="h4">Unidades</h1><th>
						<th align="center" style="vertical-align:middle"><h1 class="h4">Precio</h1><th>
            <th style="vertical-align:middle"><h1 class="h4">Acciones</h1></td>
					</thead>
					{% for productos in latest_alcohol_list %}
					<tr>

						<td align="center" style="vertical-align:middle">{{ productos.codigo_p }}<td>
						<td align="center" style="vertical-align:middle">{{ productos.nombre }}<td>
            <td align="center" style="vertical-align:middle">{{ productos.descripcion }}<td>
            <td align="center" style="vertical-align:middle">{{ productos.categoria }}<td>
						<td align="center" style="vertical-align:middle">{{ productos.unidades }}<td>
						<td align="center" style="vertical-align:middle">$ {{ productos.precio }}<td>
            <td style="vertical-align:middle">
							{% if request.user.is_superuser %}
							<a href="{% url "productos:producto_detail" productos.id %}"><button type="submit" class="btn btn-success" style="background-color: #338A11; border-color:#1bf10a;">Ver</button></a>
							<a href="{% url "productos:delete" productos.id %}"><button type="submit" class="btn btn-success" style="background-color: darkred; border-color: red;">Eliminar</button></a>
							{% else %}
							<a href="{% url "productos:producto_detail" productos.id %}"><button type="submit" class="btn btn-success" style="background-color: #338A11; border-color:#1bf10a;">Ver</button></a>
							{% endif %}
						</td>
					</tr>
        {% endfor %}

				</table>
			</div>
		</div>
{% endblock %}

tienda/templates/productos/venta_list.html
{% extends 'base.html' %}
	{% block head_title %}Lista de Ventas{% endblock %}
	{% block content %}
  {% load bootstrap3 %}
	<script type="text/javascript">
(function(document) {
  'use strict';

  var LightTableFilter = (function(Arr) {

    var _input;

    function _onInputEvent(e) {
      _input = e.target;
      var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
      Arr.forEach.call(tables, function(table) {
        Arr.forEach.call(table.tBodies, function(tbody) {
          Arr.forEach.call(tbody.rows, _filter);
        });
      });
    }

    function _filter(row) {
      var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
      row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
    }

    return {
      init: function() {
        var inputs = document.getElementsByClassName('light-table-filter');
        Arr.forEach.call(inputs, function(input) {
          input.oninput = _onInputEvent;
        });
      }
    };
  })(Array.prototype);

  document.addEventListener('readystatechange', function() {
    if (document.readyState === 'complete') {
      LightTableFilter.init();
    }
  });

})(document);
</script>

<style type="text/css">
#cuadro{
	width: 90%;
	background: #F8F8F8 ;
	padding: 25px;
	margin: 5px auto;
	border: 3px solid #D8D8D8;
}

#buscar{
	width: 300px;
	font-size: 22px;
	color: #fff;
	background: #383838 ;
	padding-left: 20px ;
	text-align: center;
	border-radius: 5px;
	padding: 10px;
	margin:10px;
}

	</style>
	<div class="row">
		<div align="center">
			<h1 style="color:white;">Lista de Ventas</h1>
			{% load staticfiles %}
			<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
			<div class="derecha" id="buscar">Buscar <input style="color:black;" type="search" class="light-table-filter" data-table="order-table" placeholder="Buscar"></div>
			<table class="order-table table">
				<thead>
						<td align="center" style="vertical-align:middle"><h1 class="h4">Id</h1><td>
						<td align="center" style="vertical-align:middle"><h1 class="h4">Producto</h1><td>
						<td align="center" style="vertical-align:middle"><h1 class="h4">Cantidad vendida</h1><td>
            <td align="center" style="vertical-align:middle"><h1 class="h4">Fecha</h1><td>
				</thead>
{{venta}}
					{% for venta in playera %}
					<tr>
						<td align="center" style="vertical-align:middle">{{ venta.id }}<td>
						<td align="center" style="vertical-align:middle">{{ venta.producto }}<td>
						<td align="center" style="vertical-align:middle">{{ venta.cantidad_vendida }}<td>
            <td align="center" style="vertical-align:middle">{{ venta.fecha }}<td>
					</tr>
        {% endfor %}

				</table>
				<form action="{% url "productos:pdfdia" %}" method="GET">
					<label for="date">Selecciona Fecha para Consultar <input type="date" style="color:black;" name="date" id="date" required="required"></label>
					<p><input type="submit" style="color:black;" value="Reporte por Fecha"></p>
			</div>
		</div>
{% endblock %}